# Generated by Django 4.0.6 on 2022-07-23 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='category name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/Category__images/', verbose_name='Category image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='package name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='package price')),
                ('detail', models.TextField(verbose_name='package details')),
                ('items', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/Package__images/', verbose_name='Package image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bm.category', verbose_name='package category')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='%Y-%m-%d %H:%M:%S')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Appointment time')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Your first name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Your last name')),
                ('email', models.CharField(max_length=100, verbose_name='Your email address')),
                ('phone', models.CharField(max_length=13, verbose_name='Your phone number')),
                ('massage', models.TextField(blank=True, null=True, verbose_name='Your massage')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bm.package', verbose_name='Appointment package')),
            ],
        ),
    ]
