# Generated by Django 4.0.6 on 2022-07-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='process',
            field=models.CharField(max_length=100, null=True, verbose_name='Process'),
        ),
        migrations.AddField(
            model_name='package',
            name='term',
            field=models.CharField(max_length=100, null=True, verbose_name='term'),
        ),
        migrations.AddField(
            model_name='package',
            name='type_of_camera',
            field=models.CharField(max_length=100, null=True, verbose_name='Type of camera'),
        ),
    ]
