# Generated by Django 4.0.6 on 2022-07-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm', '0002_package_process_package_term_package_type_of_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('image', models.ImageField(upload_to='uploads/images/team__images/', verbose_name='image')),
            ],
        ),
    ]
