# Generated by Django 4.0.6 on 2022-07-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm', '0004_alter_category_image_alter_package_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='massage',
        ),
    ]
