# Generated by Django 4.0.6 on 2022-07-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm', '0006_appointment_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Gallery name')),
                ('image', models.ImageField(null=True, upload_to='images/gallery__images/', verbose_name='Gallery image')),
                ('detail', models.TextField(null=True, verbose_name='gallery descriptions')),
            ],
        ),
    ]
